uploads = []
outputs = []

[[generated]]
id = "s-3iDTukXi1pwO9rGa3RU"
uri = "file://artifacts/zombie-shooter/public/assets/background.png"
type = "image"
title = "minara trading floor background"

[[generated]]
id = "I2_4avLB4EtI-d-dLhrnC"
uri = "file://artifacts/zombie-shooter/public/assets/shooter.png"
type = "image"
title = "shooter back view upward"

[[generated]]
id = "34pWkY9om-Ef2yz7QGVKk"
uri = "file://artifacts/zombie-shooter/public/assets/zombie.png"
type = "image"
title = "trading bear zombie enemy"

[[generated]]
id = "_iaZ-LhSnKT14jy8jYqL7"
uri = "file://artifacts/zombie-shooter/public/assets/characters/minara-core.png"
type = "image"
title = "minara core halftone"

[[generated]]
id = "MV25PXcx1WOclv8pDuVtQ"
uri = "file://artifacts/zombie-shooter/public/assets/characters/minara-hacker.png"
type = "image"
title = "minara hacker halftone"

[[generated]]
id = "eKtzJlaipKYbnkiORXTWQ"
uri = "file://artifacts/zombie-shooter/public/assets/characters/minara-arcane.png"
type = "image"
title = "minara arcane halftone"

[[generated]]
id = "Kc09S83wNuTiUHk25PQ1y"
uri = "file://artifacts/zombie-shooter/public/assets/characters/minara-cyber.png"
type = "image"
title = "minara cyber halftone"

[[generated]]
id = "g_0fnWLkEugPashawYwQ6"
uri = "file://artifacts/zombie-shooter/public/assets/characters/minara-commander.png"
type = "image"
title = "minara commander halftone"

[[generated]]
id = "B4Dfo1kkP4ZMvOlsae59o"
uri = "file://artifacts/zombie-shooter/public/assets/characters/minara-hacker-shooter.png"
type = "image"
title = "hacker shooter pose sprite"

[[generated]]
id = "vPfZqjS1ejeyeGEn-D5DQ"
uri = "file://artifacts/zombie-shooter/public/assets/characters/minara-arcane-shooter.png"
type = "image"
title = "arcane shooter pose sprite"

[[generated]]
id = "KORTPX1k-Ofm-owMoWPBB"
uri = "file://artifacts/zombie-shooter/public/assets/characters/minara-cyber-shooter.png"
type = "image"
title = "cyber shooter pose sprite"

[[generated]]
id = "sheJJiJvAtkYlUw0DP3Cw"
uri = "file://artifacts/zombie-shooter/public/assets/characters/minara-commander-shooter.png"
type = "image"
title = "commander shooter pose sprite"

[[generated]]
id = "MvlxtSLiUnAMByt-ow2M4"
uri = "file://artifacts/zombie-shooter/public/assets/characters/player-glasses-girl-shooter.png"
type = "image"
title = "glasses girl shooter sprite top down"

[[generated]]
id = "gB1ZBJzUV5Nf_krS6BVUb"
uri = "file://artifacts/zombie-shooter/public/assets/characters/player-blue-boy-shooter.png"
type = "image"
title = "Lowes single gun shooter sprite"
